### ISSUE TITLE
Text To Speech Support 

### ISSUE THREAD

**Issue by Peter-Barrett** [webOS-TV-app-samples/webOSTVJSLibrary#1]
I need to find out how to support text to speech for our visually impaired users but I can't find any documentation or examples of how to do it. At the moment, when our app is accessed with text to speech enabled on the TV, nothing happens. So it seems like we need to explicitly support the functionality but there is no documentation on how to do that. Any help would be appreciated.

**Comment by haeun3park** [comment]
@Peter-Barrett You should add supportsAudioGuidance property in appinfo.json. Check [here](https://webostv.developer.lge.com/develop/references/appinfo-json#accessibility)!
If you have any question while developing an app, ask the community in the developer site.

**Comment by Peter-Barrett** [comment]
@haeun3park thanks for that, that new documentation really helps, it's mush better!
