### ISSUE TITLE
[webOSTVjs-1.2.7] SyntaxError: Functions cannot be declared in a nested block in strict mode 

### ISSUE THREAD

**Issue by nickolaschong** [webOS-TV-app-samples/webOSTVJSLibrary#2]
Reference: https://webostv.developer.lge.com/develop/references/webostvjs-introduction
SyntaxError: Functions cannot be declared in a nested block in strict mode 

**TV Model**: 49UH600T
<img width="1001" alt="Screenshot 2023-07-15 at 5 17 32 PM" src="https://github.com/webOS-TV-app-samples/webOSTVJSLibrary/assets/25890679/642d4cce-f0b4-4d09-b627-2e83032d33be">

Script is also not backward compatible with WebOS 2.0

**Comment by haeunp** [comment]
Hi @nickolaschong ,
We have checked that webOSTV.js v1.2.7 does not currently work in webOS 3.0 or lower, and we are figuring out the cause of the issue internally.
We will release a new version as soon as it is resolved.

Thanks for reporting the issue.
We would appreciate it if you could ask questions about webOSTV.js itself, not the sample app code, to the [webOS TV developer site community](https://forum.webostv.developer.lge.com/).

**Comment by suhyunleeLge** [comment]
Dear @nickolaschong ,
The modified webOSTV.js v1.2.8 was distributed (https://webostv.developer.lge.com/assets/library/webOSTVjs-1.2.8.zip)  and the sample code was also updated. 

Thanks for waiting for the new version to be released.
