### ISSUE TITLE
Perform remote control actions to avoid sleep mode on an IPK

### ISSUE THREAD

**Issue by firodriguez** [webOS-TV-app-samples/webOSTVJSLibrary#4]
Hello,

I find this project perfect for displaying data, but do you know if it's possible to perform remote control actions to prevent the TV from entering sleep mode at a specific time? I've checked the TV settings for power-saving mode, but that doesn't seem to solve the issue. If it's possible to increase the volume periodically to keep the TV active and prevent it from entering sleep mode, that would be ideal.

Best regards.

**Comment by haeun-p** [comment]
You can increase/decrease the volume periodically by using [Audio API](https://webostv.developer.lge.com/develop/references/audio).
However, it would be extremely weird to users, so I don't recommend it unless the app is only for personal use.
If you have any further questions, please use [webOS TV Community](https://forum.webostv.developer.lge.com/).
Thanks.
